# Generated by Django 2.1 on 2018-11-09 02:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181108_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=1024),
        ),
    ]
