# Generated by Django 2.1 on 2018-11-10 10:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181108_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=3000),
        ),
    ]
